{
 "title": "Kube Metrics environmentNAME regionNAME",
 "description": "Cluster Metrics from Kube Metrics",
 "tags": [
  "kubernetes",
  "kubernetes-app"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_node_info, env)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_created{env=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{env=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{env=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}, container)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "nodename",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{env=~\"$cluster\"}, nodename) "
    }
   },
   {
    "name": "node",
    "label": "Node IP",
    "query": {
     "query": "label_values(node_uname_info{env=~\"$cluster\", nodename=\"$nodename\"}, instance)"
    }
   },
   { "name": "datasource", "query": "datasourceNAME" }
  ]
 },
 "panels": [
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Insights",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{env=~\"$cluster\", job=~\"$job\", instance=~\"$node\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{env=~\"$cluster\", job=~\"$job\", instance=~\"$node\"} / (node_memory_MemTotal_bytes{env=~\"$cluster\", job=~\"$job\", instance=~\"$node\"})))* 100",
     "legendFormat": "Memory"
    },
    {
     "expr": "max((node_filesystem_size_bytes{env=~\"$cluster\", job=~\"$job\",instance=~\"$node\", fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{env=~\"$cluster\", job=~\"$job\",instance=~\"$node\",fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {env=~\"$cluster\", job=~\"$job\",instance=~\"$node\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{env=~\"$cluster\", job=~\"$job\",instance=~\"$node\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{env=~\"$cluster\", job=~\"$job\",instance=~\"$node\",fstype=~\"ext.?|xfs\"})))",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{env=~\"$cluster\", instance=\"$node\",job=\"$job\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{env=~\"$cluster\", instance=\"$node\",job=\"$job\"} - node_boot_time_seconds{env=~\"$cluster\", instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{env=~\"$cluster\", instance=\"$node\"})"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{env=~\"$cluster\", instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (avg without (cpu)(irate(node_cpu_seconds_total{job=\"$job\",instance=\"$node\",mode=\"idle\"}[5m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{env=~\"$cluster\", job=~\"$job\", instance=~\"$node\"} / (node_memory_MemTotal_bytes{env=~\"$cluster\", job=~\"$job\", instance=~\"$node\"})))* 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{cluster=~\"$cluster\", job=~\"$job\", instance=~\"$node\"} - node_memory_MemFree_bytes{cluster=~\"$cluster\", job=~\"$job\", instance=~\"$node\"} - node_memory_Buffers_bytes{cluster=~\"$cluster\", job=~\"$job\", instance=~\"$node\"} - node_memory_Cached_bytes{cluster=~\"$cluster\", job=~\"$job\", instance=~\"$node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{cluster=~\"$cluster\", job=~\"$job\", instance=~\"$node\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{cluster=~\"$cluster\", job=~\"$job\", instance=~\"$node\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{cluster=~\"$cluster\", job=~\"$job\", instance=~\"$node\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Usage",
     "type": "gauge",
     "description": "The average CPU usage of all the nodes in the cluster.",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(100 - (avg by (node) (rate(node_cpu_seconds_total{env=~\"$cluster\", mode=\"idle\"}[5m])) * 100))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "gauge",
     "description": "The memory usage in percentage of all nodes in the cluster.",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum (node_memory_MemTotal_bytes{env=~\"$cluster\"}) - sum (node_memory_MemAvailable_bytes{env=~\"$cluster\"})) / sum (node_memory_MemTotal_bytes{env=~\"$cluster\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Server Capacity",
     "type": "table",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 22 },
     "targets": [
      {
       "expr": "100 - ((avg by (instance) (irate(node_cpu_seconds_total{env=~\"$cluster\", job=~\"$job\", mode=\"idle\"}[5m]))) * 100)",
       "legendFormat": "CPU"
      },
      {
       "expr": "(1 - ((sum by (instance) (node_memory_MemAvailable_bytes{env=~\"$cluster\", job=~\"$job\"})) / (sum by (instance) ((node_memory_MemTotal_bytes{env=~\"$cluster\", job=~\"$job\"})))))* 100",
       "legendFormat": "Memory"
      },
      {
       "expr": "(max by (instance) ((node_filesystem_size_bytes{env=~\"$cluster\", job=~\"$job\", fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{env=~\"$cluster\", job=~\"$job\",fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {env=~\"$cluster\", job=~\"$job\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{env=~\"$cluster\", job=~\"$job\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{env=~\"$cluster\", job=~\"$job\",fstype=~\"ext.?|xfs\"}))))",
       "legendFormat": "Disk"
      },
      {
       "expr": " sum by (instance)(count without (job,mode) (node_cpu_seconds_total{env=\"$cluster\", job=\"$job\",mode=\"idle\"}))"
      }
     ]
    },
    {
     "title": "Number Of Nodes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_info{env=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Nodes Unavailable",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_spec_unschedulable{env=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "CPU Usage - All",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(1 - avg(irate(node_cpu_seconds_total{job=\"$job\", mode=\"idle\"}[5m])) by (instance)) * 100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory Usage - All",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(1 - (sum by (instance) (node_memory_MemAvailable_bytes{env=~\"$cluster\", job=~\"$job\"}) / sum by (instance) (node_memory_MemTotal_bytes{env=~\"$cluster\", job=~\"$job\"}))) * 100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Node Number",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_node_info{env=~\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory & CPU usage per container",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "max(kube_pod_container_resource_requests{env=~\"$cluster\", resource=\"memory\"}) by (pod)"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{env=~\"$cluster\", resource=\"memory\"}) by (pod)"
      },
      {
       "expr": "max(container_memory_working_set_bytes{cluster=~\"$cluster\", name!=\"\"}) by (pod)"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{env=~\"$cluster\", resource=\"cpu\"}) by (pod)"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{env=~\"$cluster\", resource=\"cpu\"}) by (pod)"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", image!=\"\", container_name!=\"POD\"}[5m])) by (pod)"
      },
      {
       "expr": "max(kube_pod_info{env=~\"$cluster\"}) by (pod,namespace,node)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Usage by namespace(mcores)",
     "type": "bargauge",
     "description": "The CPU usage in a cluster grouped by Kubernetes namespace",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum by (namespace) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", container!=\"\", container!=\"POD\"}[5m]) * 1000))",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "CPU Usage by deployment(mcores)",
     "type": "bargauge",
     "description": "The CPU usage in a cluster grouped by Kubernetes deployment",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum by (container, namespace) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", container!=\"\", container!=\"POD\"}[5m]) * 1000))",
       "legendFormat": "{{ namespace }} - {{container}}"
      }
     ]
    },
    {
     "title": "CPU Usage by pod(mcores)",
     "type": "bargauge",
     "description": "The CPU usage in a cluster grouped by Kubernetes pod",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum by (pod, namespace) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", container!=\"\", container!=\"POD\"}[5m]) * 1000))",
       "legendFormat": "{{ namespace }} - {{ pod}}"
      }
     ]
    },
    {
     "title": "Memory usage by namespace",
     "type": "bargauge",
     "description": "The memory usage in a cluster grouped by Kubernetes namespace",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum by (namespace) (container_memory_working_set_bytes{cluster=~\"$cluster\", pod!=\"\",container!=\"POD\", container!=\"\"}))",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Memory usage by deployment",
     "type": "bargauge",
     "description": "The memory usage in a cluster grouped by Kubernetes deployment",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum by (container, namespace) (container_memory_working_set_bytes{cluster=~\"$cluster\", container!=\"POD\", container!=\"\"}))",
       "legendFormat": "{{ namespace }} - {{ container}}"
      }
     ]
    },
    {
     "title": "Memory usage by pod",
     "type": "bargauge",
     "description": "The memory usage in a cluster grouped by Kubernetes pod",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum by (pod, namespace) (container_memory_working_set_bytes{cluster=~\"$cluster\", pod!=\"\",container!=\"POD\", container!=\"\"}))",
       "legendFormat": "{{ namespace }} - {{ pod}}"
      }
     ]
    },
    {
     "title": "Pod CPU usage (mcores)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", image!=\"\", container_name!=\"POD\"}[5m]) * 1000) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Total pod memory usage",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{cluster=~\"$cluster\", image!=\"\", container_name!=\"POD\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Deployment Replicas - Up To Date",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 90 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas{env=~\"$cluster\", namespace=~\"$namespace\"}",
       "legendFormat": "{{ deployment }}"
      }
     ]
    },
    {
     "title": "Deployment Replicas",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas{env=~\"$cluster\", namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Deployment Replicas - Updated",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_updated{env=~\"$cluster\", namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Deployment Replicas - Unavailable",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_unavailable{env=~\"$cluster\", namespace=~\"$namespace\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Statefuleset",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Statefulset Replicas - Up To Date",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 91 },
     "targets": [
      {
       "expr": "kube_statefulset_status_replicas_ready{env=~\"$cluster\", namespace=~\"$namespace\"}",
       "legendFormat": "{{ statefulset}}"
      }
     ]
    },
    {
     "title": "Statefulset replicas",
     "type": "graph",
     "gridPos": { "h": 5, "w": 18, "x": 6, "y": 91 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "kube_statefulset_status_replicas_ready{env=~\"$cluster\", namespace=~\"$namespace\"}/kube_statefulset_status_replicas{env=~\"$cluster\", namespace=~\"$namespace\"}*100",
       "legendFormat": "{{statefulset}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Pods restart in 30m",
     "type": "table-old",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 92 },
     "targets": [
      {
       "expr": "changes(kube_pod_container_status_restarts_total{env=~\"$cluster\", namespace=~\"$namespace\"}[30m])>1",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Evicted",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 92 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_pod_status_reason{env=~\"$cluster\", namespace=~\"$namespace\", reason=\"Evicted\"}==1",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pods Running",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{env=~\"$cluster\", namespace=~\"$namespace\", phase=\"Running\"})"
      }
     ]
    },
    {
     "title": "Pods Succeeded",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{env=~\"$cluster\", namespace=~\"$namespace\", phase=\"Succeeded\"})"
      }
     ]
    },
    {
     "title": "Pods Failed",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{env=~\"$cluster\", namespace=~\"$namespace\", phase=\"Failed\"})"
      }
     ]
    },
    {
     "title": "Pods Pending",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{env=~\"$cluster\", namespace=~\"$namespace\", phase=\"Pending\"})"
      }
     ]
    },
    {
     "title": "Pods Unknown",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{env=~\"$cluster\", namespace=~\"$namespace\", phase=\"Unknown\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Containers Running",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_running{env=~\"$cluster\", namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Containers Waiting",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_waiting{env=~\"$cluster\", namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Containers Terminated",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_terminated{env=~\"$cluster\", namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Containers Restarts (Last 30 Minutes)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(changes(kube_pod_container_status_restarts_total{env=~\"$cluster\", namespace=~\"$namespace\"})[30m])"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Jobs Succeeded",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_job_status_succeeded{env=~\"$cluster\", namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Job last success time from now",
     "type": "table-old",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 94 },
     "targets": [
      {
       "expr": "(time()-kube_job_status_completion_time{env=~\"$cluster\", namespace=~\"$namespace\"})/60/60/24>1",
       "legendFormat": "{{job_name}}"
      }
     ]
    },
    {
     "title": "Job failed",
     "type": "table-old",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 94 },
     "targets": [
      {
       "expr": "kube_job_status_failed{env=~\"$cluster\", namespace=~\"$namespace\"}>1",
       "legendFormat": "{{job_name}}"
      }
     ]
    },
    {
     "title": "Jobs Active",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_job_status_active{env=~\"$cluster\", namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Jobs Failed",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_job_status_failed{env=~\"$cluster\", namespace=~\"$namespace\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "PVC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "pvc is bound",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_persistentvolumeclaim_status_phase{env=~\"$cluster\", phase=\"Bound\"}==1)",
       "legendFormat": "{{persistentvolumeclaim=}}"
      }
     ]
    },
    {
     "title": "pvc is not bound",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_persistentvolumeclaim_status_phase{env=~\"$cluster\", phase!=\"Bound\"}==1)",
       "legendFormat": "{{persistentvolumeclaim=}}"
      }
     ]
    },
    {
     "title": "pvc",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
     "targets": [
      {
       "expr": "kube_persistentvolumeclaim_resource_requests_storage_bytes{env=~\"$cluster\"}/1024/1024/1024",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    }
   ]
  }
 ]
}