{
 "title": "Log Dashboard environmentNAME regionNAME",
 "description": "Container/Pod Log Dashboard(Loki as DataSource)",
 "tags": [
  "Loki",
  "logging"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values({namespace=~\".+\"}, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values({namespace=\"$namespace\"}, pod)"
   },
   {
    "name": "stream",
    "label": "Stream",
    "query": "label_values({namespace=\"$namespace\"}, stream)"
   },
   { "name": "searchable_pattern", "label": "Search (case insensitive)" },
   { "name": "datasource", "query": "datasourceNAME" }
  ]
 },
 "panels": [
  {
   "title": "Live logs",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", pod=~\"$pod\", stream=~\"$stream\"} |~ \"(?i)$searchable_pattern\" "
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Application Error Detected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(pod, namespace, env, msg) (count_over_time({job=~\".+\", namespace!=\"loki\"} | logfmt |= \"level=error\" != \"there is no access token inside the header\" !=\"json: cannot unmarshal array into Go struct field JWTAccessClaims.aud of type string\" !=\"empty status code\" | __error__!=\"LogfmtParserErr\"[5m]))"
    }
   ]
  },
  {
   "title": "Same IP Multiple Times Detected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by(ip_address, uri) (count_over_time({namespace=\"ingress-nginx\"}| regexp \"(?P<ip_address>\\\\b(?:[0-9]{1,3}\\\\.){3}[0-9]{1,3}\\\\b)\" | pattern \"<_> <_> <_> <_> <_> <_> <_> <_> <_> <uri> <_>\"[5m]))"
    }
   ]
  },
  {
   "title": "PII Detected Or Keyword Found",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by(pod, namespace, env, msg, args) (count_over_time({namespace=\"apps\"} | logfmt |~ `(?i)\\b(?:[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,})\\b|\\b(?:\\d{3}[-.\\s]?\\d{2}[-.\\s]?\\\\d{4})\\b|\\b(?:\\d{3}[-.\\s]?\\d{3}[-.\\s]?\\d{4})\\b|\\b\\d{10,15}\\b` | __error__!=\"LogfmtParserErr\" [5m]))"
    }
   ]
  },
  {
   "title": "Unauthorized Access Detected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by(pod, namespace, env)(count_over_time({job=~\".+\", namespace!=\"loki\"} | logfmt |= \"status=401\" | __error__!=\"LogfmtParserErr\"[5m]))"
    }
   ]
  },
  {
   "title": "SQL Injection Detected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by(pod, namespace, env, sql)(\n  count_over_time(\n    {job=~\".+\", namespace!=\"loki\", sql=~\"(?i)(OR 1=1|UNION SELECT|--|;--|; DROP|-- DROP|\\\\bSELECT\\\\b.*\\\\bFROM\\\\b.*--|\\\\bDELETE\\\\b.*\\\\bFROM\\\\b.*--|\\\\bINSERT\\\\b.*\\\\bINTO\\\\b.*--|\\\\bUPDATE\\\\b.*\\\\bSET\\\\b.*--)\"} \n    | logfmt \n    | __error__!=\"LogfmtParserErr\"[5m]\n  )\n)"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Info Type Logs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", stream=~\"$stream\", pod=~\"$pod\"}|~\"info\"[$__range]))"
    }
   ]
  },
  {
   "title": "Warning Type Logs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", stream=~\"$stream\", pod=~\"$pod\"}|~\"warn|warning\"[$__range])) "
    }
   ]
  },
  {
   "title": "Error Type Logs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", stream=~\"$stream\", pod=~\"$pod\"}|~\"error\"[$__range])) "
    }
   ]
  },
  {
   "title": "Bug Type Logs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", stream=~\"$stream\", pod=~\"$pod\"}|~\"bug\"[$__range])) "
    }
   ]
  },
  {
   "title": "\"$searchable_pattern\" Rate per Pod",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(({namespace=\"$namespace\", stream=~\"$stream\", pod=~\"$pod\"} |~ \"(?i)$searchable_pattern\")[30s])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Requests per status code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (status_code) (count_over_time({namespace=\"$namespace\", stream=~\"$stream\", pod=~\"$pod\"} \n| pattern `<_> \"<method> <path> <protocol>\" <status_code> <response_flags> <response_code_details> <connection_termination_details> \"<failure_reason>\" <bytes_received> <bytes_sent> <duration> <upstream_time> \"<forward_for>\" \"<agent>\" \"<req_id>\" \"<authority>\" \"<upstream_host>\" <upstream_cluster> <upstream_local_address> <downstream_local_address> <downstream_remote_address> <requested_server_name> <route_name>`  | __error__=\"\"\n | status_code =~\"0|2..|3..|4..|5..\" \n[$__interval])) ",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Log lines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({namespace=\"$namespace\", stream=~\"$stream\", pod=~\"$pod\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Logs in bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "bytes_over_time({namespace=\"$namespace\", stream=~\"$stream\", pod=~\"$pod\"}[$__interval])",
     "legendFormat": "$label_value"
    }
   ]
  },
  {
   "title": "Requests per status code with time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status_code) (count_over_time({namespace=\"$namespace\", stream=~\"$stream\", pod=~\"$pod\"} \n| pattern `<_> \"<method> <path> <protocol>\" <status_code> <response_flags> <response_code_details> <connection_termination_details> \"<failure_reason>\" <bytes_received> <bytes_sent> <duration> <upstream_time> \"<forward_for>\" \"<agent>\" \"<req_id>\" \"<authority>\" \"<upstream_host>\" <upstream_cluster> <upstream_local_address> <downstream_local_address> <downstream_remote_address> <requested_server_name> <route_name>`  | __error__=\"\"\n | status_code =~\"0|2..|3..|4..|5..\" \n[$__interval])) "
    }
   ]
  },
  {
   "title": "Top 10 Visitor IPs",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(ip_address) (count_over_time({namespace=\"ingress-nginx\"}| regexp \"(?P<ip_address>\\\\b(?:[0-9]{1,3}\\\\.){3}[0-9]{1,3}\\\\b)\"[5m])) ",
     "legendFormat": "{{ip_address}}"
    }
   ]
  },
  {
   "title": "Matched word: \"$searchable_pattern\" donut",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 56 },
   "format": "short",
   "valueName": "total",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({namespace=\"$namespace\", pod=~\"$pod\", stream=~\"$stream\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Matched word: \"$searchable_pattern\" historical",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time(({namespace=\"$namespace\", pod=~\"$pod\", stream=~\"$stream\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Count of stderr / stdout",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time(({namespace=\"$namespace\", pod=~\"$pod\"})[$__interval])) by (stream)"
    }
   ]
  }
 ]
}