apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
  labels:
    app: patient-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      containers:
      - name: patient-service
        image: 539935451710.dkr.ecr.us-east-1.amazonaws.com/hackathon-devops-riju-patient:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
