apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
  labels:
    app: appointment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
      - name: appointment-service
        image: 539935451710.dkr.ecr.us-east-1.amazonaws.com/hackathon-devops-appointment:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3001"
